site_name: Biología
nav:
  - La Célula:
      - Introducción: cell.md
      - Tipos de células:
        - La Célula Eucariota: eukaryote.md
        - La Célula Procariota: prokaryote.md
  - Enfermedades:
      - Introducción: disease.md
      - Tipos de contagio:
          - Infecciosas: infection.md
theme:
  name: material
  language: es
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
site_url: https://github.com/AlejandroBM99/mkdocs-biology