site_name: Biología
nav:
  - La Célula: cell.md
  - Enfermedades:
      - Introducción: disease.md
      - Tipos de contagio:
          - Infecciosas: infection.md
          - No infecciosas: non-infection.md
theme:
  name: material
  language: es
site_url: https://github.com/AlejandroBM99/mkdocs-biology