site_name: Biología
nav:
  - La Célula:
      - Introducción: cell.md
      - Tipos de células:
        - La Célula Eucariota: eukaryote.md
        - La Célula Procariota: prokaryote.md
  - Enfermedades:
      - Introducción: disease.md
      - Tipos de contagio:
          - Infecciosas: infection.md
          - No infecciosas:
theme:
  name: material
  language: es
site_url: https://github.com/AlejandroBM99/mkdocs-biology