site_name: Biología
site_url: https://github.com/AlejandroBM99/mkdocs-biology
theme:
  name: material
  custom_dir: overrides
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotate
    - search.highlight
  palette:
    - scheme: default
      primary: lime
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Claro
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Oscuro
extra:
  social:
    - icon: material/github
      link: https://github.com/AlejandroBM99/mkdocs-biology
    - icon: material/web-box
      link: https://alejandrobm99.github.io/mkdocs-biology/
    - icon: custom/mm_logo
      link: https://www.msdmanuals.com/es/hogar/health-topics
  navigation:
    title: Menú Principal
extra_css:
  - css/custom.css
extra_javascript:
  - js/popup.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - mermaid:javascript
plugins:
  - search
  - mermaid2:
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
nav:
  - Inicio: index.md
  - La Célula:
      - Introducción: cell/cell.md
      - Tejidos: cell/tissue.md
  - Sistemas y aparatos:
      - Introducción: organization/system.md
      - Los cinco sentidos: organization/sense.md
      - Funciones del cuerpo humano: organization/function.md
      - Lista de aparatos:
          - Aparato digestivo: system/digestive.md
          - Aparato respiratorio: system/respiratory.md
          - Aparato locomotor: system/locomotor.md
          - Aparato circulatorio: system/circulatory.md
          - Aparato excretor: system/excretory.md
          - Aparato reproductor: system/reproductive.md
          - Sistema endocrino: system/endocrine.md
          - Sistema nervioso: system/nervous.md
      - Sistemas:
          - Sistema esquelético: system/skeleton.md
          - Sistema muscular: system/muscular.md
  - Enfermedades:
      - Introducción: disease/disease.md
      - Tipos de contagio:
          - Infecciosas: disease/infection.md
          - No infecciosas: disease/non-infection.md
